import 'dart:ui';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

// Supported languages
enum AppLanguage {
  system('system', 'System'),
  english('en', 'English'),
  simplifiedChinese('zh-Hans', '简体中文'),
  traditionalChinese('zh-Hant', '繁體中文'),
  japanese('ja', '日本語'),
  korean('ko', '한국어'),
  french('fr', 'Français'),
  german('de', 'Deutsch');

  final String code;
  final String displayName;

  const AppLanguage(this.code, this.displayName);

  static AppLanguage fromCode(String code) {
    return AppLanguage.values.firstWhere(
      (lang) => lang.code == code,
      orElse: () => AppLanguage.system,
    );
  }
}

// Localization keys
enum L {
  // Menu
  gameTitle,
  startGame,
  settings,
  controls,
  leaderboard,
  badges,
  badgeUnlocked,
  badgeLocked,
  tapToClose,
  errorConnectWalletFirst,
  errorAuthFailed,
  errorLoadBadgesFailed,
  exitConfirmTitle,
  exitConfirmMessage,
  exitConfirmYes,
  exitConfirmNo,
  quit,

  // Pause
  paused,
  resume,
  restart,
  mainMenu,

  // Game Over
  gameOver,
  finalScore,
  level,
  lines,
  maxCombo,
  time,
  playAgain,

  // HUD
  score,
  next,
  hold,
  combo,

  // Settings
  settingsTitle,
  visual,
  glowIntensity,
  glitchEffects,
  audio,
  soundEffects,
  volume,
  music,
  musicVolume,
  hapticFeedback,
  language,
  languageSettings,

  // Controls
  controlsTitle,
  moveLeft,
  moveRight,
  softDrop,
  hardDrop,
  rotateCW,
  rotateCCW,
  holdPiece,
  pause,

  // Leaderboard
  rank,
  playerName,
  noRecords,
  playToRecord,
  newHighScore,
  yourRank,
  enterName,
  submit,
  skip,

  // Controls screen
  touchControls,
  tips,
  tip1,
  tip2,
  tip3,

  // Pause
  tapToResume,

  // Wallet Binding
  bindWallet,
  connectWallet,
  unlockGlobalRank,
  bindDescription,
  benefitGlobalRanking,
  benefitCloudSync,
  benefitAchievements,
  connectingWallet,
  binding,
  processing,
  openWalletApp,
  walletConnected,
  unbind,
  unbindConfirm,
  cancel,

  // Sync Score
  syncScores,
  syncScoresDescription,
  selected,
  uploading,
  upload,
  uploadToGlobal,

  // Global Leaderboard
  localTab,
  globalTab,
  globalLocked,
  bindNow,
  willSyncToCloud,
  syncedToCloud,
  submitting,

  // Wallet Picker
  selectWallet,
  selectWalletApp,
  recommended,
  bestMwaSupport,
  mwaSupported,
  deepLinkSupported,
  walletTip,
  walletTipContent,
  clearDefaults,
  noWalletShowQr,
  downloadWallet,
  scanWithWallet,
  walletNotInstalled,
}

class LocalizationService extends ChangeNotifier {
  static final LocalizationService _instance = LocalizationService._internal();
  static LocalizationService get instance => _instance;
  LocalizationService._internal();

  static const _languageKey = 'app_language';

  AppLanguage _currentLanguage = AppLanguage.system;
  AppLanguage get currentLanguage => _currentLanguage;

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final code = prefs.getString(_languageKey) ?? 'system';
    _currentLanguage = AppLanguage.fromCode(code);
    notifyListeners();
  }

  Future<void> setLanguage(AppLanguage language) async {
    _currentLanguage = language;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, language.code);
    notifyListeners();
  }

  /// Get the effective language code for API requests
  String get apiLanguageCode => effectiveLanguage.code;

  /// Get the effective language (resolves 'system' to actual device language)
  AppLanguage get effectiveLanguage => _effectiveLanguage;

  AppLanguage get _effectiveLanguage {
    if (_currentLanguage != AppLanguage.system) {
      return _currentLanguage;
    }

    // Get device language
    final locale = PlatformDispatcher.instance.locale;
    final languageCode = locale.languageCode;
    final scriptCode = locale.scriptCode;
    final countryCode = locale.countryCode;

    if (languageCode == 'zh') {
      if (scriptCode == 'Hans' || countryCode == 'CN') {
        return AppLanguage.simplifiedChinese;
      } else if (scriptCode == 'Hant' || countryCode == 'TW' || countryCode == 'HK') {
        return AppLanguage.traditionalChinese;
      }
      return AppLanguage.simplifiedChinese;
    } else if (languageCode == 'ja') {
      return AppLanguage.japanese;
    } else if (languageCode == 'ko') {
      return AppLanguage.korean;
    } else if (languageCode == 'fr') {
      return AppLanguage.french;
    } else if (languageCode == 'de') {
      return AppLanguage.german;
    }

    return AppLanguage.english;
  }

  String tr(L key) {
    final lang = _effectiveLanguage;
    final strings = _strings[lang] ?? _strings[AppLanguage.english]!;
    return strings[key] ?? key.name;
  }

  // Localized strings database
  static final Map<AppLanguage, Map<L, String>> _strings = {
    // English
    AppLanguage.english: {
      L.gameTitle: 'CYBER BLOCKX',
      L.startGame: 'START GAME',
      L.settings: 'SETTINGS',
      L.controls: 'CONTROLS',
      L.leaderboard: 'LEADERBOARD',
      L.badges: 'BADGES',
      L.badgeUnlocked: 'UNLOCKED',
      L.badgeLocked: 'LOCKED',
      L.tapToClose: 'Tap anywhere to close',
      L.errorConnectWalletFirst: 'Please connect wallet first',
      L.errorAuthFailed: 'Authentication failed',
      L.errorLoadBadgesFailed: 'Failed to load badges',
      L.exitConfirmTitle: 'Exit Game',
      L.exitConfirmMessage: 'Are you sure you want to exit?',
      L.exitConfirmYes: 'EXIT',
      L.exitConfirmNo: 'CANCEL',
      L.quit: 'QUIT',
      L.paused: 'PAUSED',
      L.resume: 'RESUME',
      L.restart: 'RESTART',
      L.mainMenu: 'MAIN MENU',
      L.gameOver: 'GAME OVER',
      L.finalScore: 'Final Score',
      L.level: 'Level',
      L.lines: 'Lines',
      L.maxCombo: 'Max Combo',
      L.time: 'Time',
      L.playAgain: 'PLAY AGAIN',
      L.score: 'SCORE',
      L.next: 'NEXT',
      L.hold: 'HOLD',
      L.combo: 'COMBO',
      L.settingsTitle: 'SETTINGS',
      L.visual: 'VISUAL',
      L.glowIntensity: 'Glow Intensity',
      L.glitchEffects: 'Glitch Effects',
      L.audio: 'AUDIO',
      L.soundEffects: 'Sound Effects',
      L.volume: 'Volume',
      L.music: 'Music',
      L.musicVolume: 'Music Volume',
      L.hapticFeedback: 'Haptic Feedback',
      L.language: 'LANGUAGE',
      L.languageSettings: 'Language',
      L.controlsTitle: 'CONTROLS',
      L.moveLeft: 'Move Left',
      L.moveRight: 'Move Right',
      L.softDrop: 'Soft Drop',
      L.hardDrop: 'Hard Drop',
      L.rotateCW: 'Rotate CW',
      L.rotateCCW: 'Rotate CCW',
      L.holdPiece: 'Hold',
      L.pause: 'Pause',
      L.rank: 'Rank',
      L.playerName: 'Player',
      L.noRecords: 'No Records Yet',
      L.playToRecord: 'Play a game to set a record!',
      L.newHighScore: 'NEW HIGH SCORE',
      L.yourRank: 'Your Rank:',
      L.enterName: 'ENTER YOUR NAME',
      L.submit: 'SUBMIT',
      L.skip: 'SKIP',
      L.touchControls: 'Touch Controls',
      L.tips: 'Tips',
      L.tip1: 'Hold left/right buttons to move continuously',
      L.tip2: 'Use hard drop for quick placement',
      L.tip3: 'Hold piece to save for later',
      L.tapToResume: 'Tap RESUME to continue',
      // Wallet Binding
      L.bindWallet: 'BIND WALLET',
      L.connectWallet: 'Connect Wallet',
      L.unlockGlobalRank: 'Unlock Global Rank',
      L.bindDescription: 'Connect your Solana wallet to unlock global leaderboard and cloud sync features.',
      L.benefitGlobalRanking: 'Global Ranking',
      L.benefitCloudSync: 'Cloud Score Sync',
      L.benefitAchievements: 'Achievements',
      L.connectingWallet: 'Connecting wallet...',
      L.binding: 'Binding account...',
      L.processing: 'Processing...',
      L.openWalletApp: 'Please open your wallet app to approve the connection',
      L.walletConnected: 'Wallet Connected',
      L.unbind: 'Unbind',
      L.unbindConfirm: 'Are you sure you want to unbind your wallet? Your cloud scores will remain but you will need to rebind to access them.',
      L.cancel: 'Cancel',
      // Sync Score
      L.syncScores: 'Sync Scores',
      L.syncScoresDescription: 'You have local scores that can be uploaded to the global leaderboard. Select the scores you want to sync.',
      L.selected: 'selected',
      L.uploading: 'Uploading...',
      L.upload: 'Upload',
      L.uploadToGlobal: 'Upload to Global',
      // Global Leaderboard
      L.localTab: 'LOCAL',
      L.globalTab: 'GLOBAL',
      L.globalLocked: 'Connect your wallet to view global rankings',
      L.bindNow: 'BIND NOW',
      L.willSyncToCloud: 'Will sync to global leaderboard',
      L.syncedToCloud: 'Synced',
      L.submitting: 'Submitting...',
      // Wallet Picker
      L.selectWallet: 'Select Wallet',
      L.selectWalletApp: 'Select wallet app:',
      L.recommended: 'Recommended',
      L.bestMwaSupport: 'Best MWA support',
      L.mwaSupported: 'MWA supported',
      L.deepLinkSupported: 'Deep link supported',
      L.walletTip: 'Tip',
      L.walletTipContent: 'If the wrong wallet opens, clear its defaults first:',
      L.clearDefaults: 'Settings',
      L.noWalletShowQr: 'No wallet app? Show QR code',
      L.downloadWallet: 'Download a wallet:',
      L.scanWithWallet: 'Scan with wallet app',
      L.walletNotInstalled: '{wallet} is not installed. Please install it from the app store first.',
    },

    // Simplified Chinese
    AppLanguage.simplifiedChinese: {
      L.gameTitle: '赛博方块',
      L.startGame: '开始游戏',
      L.settings: '设置',
      L.controls: '操作说明',
      L.leaderboard: '排行榜',
      L.badges: '徽章',
      L.badgeUnlocked: '已解锁',
      L.badgeLocked: '未解锁',
      L.tapToClose: '点击任意位置关闭',
      L.errorConnectWalletFirst: '请先连接钱包',
      L.errorAuthFailed: '认证失败',
      L.errorLoadBadgesFailed: '加载徽章失败',
      L.exitConfirmTitle: '退出游戏',
      L.exitConfirmMessage: '确定要退出吗？',
      L.exitConfirmYes: '退出',
      L.exitConfirmNo: '取消',
      L.quit: '退出',
      L.paused: '暂停',
      L.resume: '继续',
      L.restart: '重新开始',
      L.mainMenu: '主菜单',
      L.gameOver: '游戏结束',
      L.finalScore: '最终得分',
      L.level: '等级',
      L.lines: '消除行数',
      L.maxCombo: '最大连击',
      L.time: '时间',
      L.playAgain: '再玩一次',
      L.score: '得分',
      L.next: '下一个',
      L.hold: '暂存',
      L.combo: '连击',
      L.settingsTitle: '设置',
      L.visual: '视觉',
      L.glowIntensity: '发光强度',
      L.glitchEffects: '故障效果',
      L.audio: '音频',
      L.soundEffects: '音效',
      L.volume: '音量',
      L.music: '音乐',
      L.musicVolume: '音乐音量',
      L.hapticFeedback: '触觉反馈',
      L.language: '语言',
      L.languageSettings: '语言设置',
      L.controlsTitle: '操作说明',
      L.moveLeft: '左移',
      L.moveRight: '右移',
      L.softDrop: '软降',
      L.hardDrop: '硬降',
      L.rotateCW: '顺时针旋转',
      L.rotateCCW: '逆时针旋转',
      L.holdPiece: '暂存',
      L.pause: '暂停',
      L.rank: '排名',
      L.playerName: '玩家',
      L.noRecords: '暂无记录',
      L.playToRecord: '开始游戏创建记录！',
      L.newHighScore: '新高分',
      L.yourRank: '你的排名：',
      L.enterName: '输入你的名字',
      L.submit: '提交',
      L.skip: '跳过',
      L.touchControls: '触摸操作',
      L.tips: '提示',
      L.tip1: '长按左/右按钮可连续移动',
      L.tip2: '使用硬降快速放置方块',
      L.tip3: '使用暂存保留方块稍后使用',
      L.tapToResume: '点击继续恢复游戏',
      // Wallet Binding
      L.bindWallet: '绑定钱包',
      L.connectWallet: '连接钱包',
      L.unlockGlobalRank: '解锁全球排名',
      L.bindDescription: '连接你的 Solana 钱包，解锁全球排行榜和云端同步功能。',
      L.benefitGlobalRanking: '全球排名',
      L.benefitCloudSync: '云端分数同步',
      L.benefitAchievements: '成就系统',
      L.connectingWallet: '正在连接钱包...',
      L.binding: '正在绑定账户...',
      L.processing: '处理中...',
      L.openWalletApp: '请打开你的钱包应用确认连接',
      L.walletConnected: '钱包已连接',
      L.unbind: '解绑',
      L.unbindConfirm: '确定要解绑钱包吗？你的云端分数会保留，但需要重新绑定才能访问。',
      L.cancel: '取消',
      // Sync Score
      L.syncScores: '同步分数',
      L.syncScoresDescription: '你有本地分数可以上传到全球排行榜。选择你想同步的分数。',
      L.selected: '已选择',
      L.uploading: '上传中...',
      L.upload: '上传',
      L.uploadToGlobal: '上传到全球榜',
      // Global Leaderboard
      L.localTab: '本地',
      L.globalTab: '全球',
      L.globalLocked: '连接钱包查看全球排名',
      L.bindNow: '立即绑定',
      L.willSyncToCloud: '将同步到全球排行榜',
      L.syncedToCloud: '已同步',
      L.submitting: '提交中...',
      // Wallet Picker
      L.selectWallet: '选择钱包',
      L.selectWalletApp: '选择钱包应用：',
      L.recommended: '推荐',
      L.bestMwaSupport: 'MWA 支持最佳',
      L.mwaSupported: '支持 MWA',
      L.deepLinkSupported: '支持深度链接',
      L.walletTip: '提示',
      L.walletTipContent: '如果打开了错误的钱包，请先清除其默认设置：',
      L.clearDefaults: '设置',
      L.noWalletShowQr: '没有钱包？显示二维码',
      L.downloadWallet: '下载钱包：',
      L.scanWithWallet: '使用钱包应用扫描',
      L.walletNotInstalled: '未安装 {wallet}，请先从应用商店安装。',
    },

    // Traditional Chinese
    AppLanguage.traditionalChinese: {
      L.gameTitle: '賽博方塊',
      L.startGame: '開始遊戲',
      L.settings: '設定',
      L.controls: '操作說明',
      L.leaderboard: '排行榜',
      L.badges: '徽章',
      L.badgeUnlocked: '已解鎖',
      L.badgeLocked: '未解鎖',
      L.tapToClose: '點擊任意位置關閉',
      L.errorConnectWalletFirst: '請先連接錢包',
      L.errorAuthFailed: '認證失敗',
      L.errorLoadBadgesFailed: '載入徽章失敗',
      L.exitConfirmTitle: '退出遊戲',
      L.exitConfirmMessage: '確定要退出嗎？',
      L.exitConfirmYes: '退出',
      L.exitConfirmNo: '取消',
      L.quit: '退出',
      L.paused: '暫停',
      L.resume: '繼續',
      L.restart: '重新開始',
      L.mainMenu: '主選單',
      L.gameOver: '遊戲結束',
      L.finalScore: '最終得分',
      L.level: '等級',
      L.lines: '消除行數',
      L.maxCombo: '最大連擊',
      L.time: '時間',
      L.playAgain: '再玩一次',
      L.score: '得分',
      L.next: '下一個',
      L.hold: '暫存',
      L.combo: '連擊',
      L.settingsTitle: '設定',
      L.visual: '視覺',
      L.glowIntensity: '發光強度',
      L.glitchEffects: '故障效果',
      L.audio: '音訊',
      L.soundEffects: '音效',
      L.volume: '音量',
      L.music: '音樂',
      L.musicVolume: '音樂音量',
      L.hapticFeedback: '觸覺回饋',
      L.language: '語言',
      L.languageSettings: '語言設定',
      L.controlsTitle: '操作說明',
      L.moveLeft: '左移',
      L.moveRight: '右移',
      L.softDrop: '軟降',
      L.hardDrop: '硬降',
      L.rotateCW: '順時針旋轉',
      L.rotateCCW: '逆時針旋轉',
      L.holdPiece: '暫存',
      L.pause: '暫停',
      L.rank: '排名',
      L.playerName: '玩家',
      L.noRecords: '暫無記錄',
      L.playToRecord: '開始遊戲創建記錄！',
      L.newHighScore: '新高分',
      L.yourRank: '你的排名：',
      L.enterName: '輸入你的名字',
      L.submit: '提交',
      L.skip: '跳過',
      L.touchControls: '觸控操作',
      L.tips: '提示',
      L.tip1: '長按左/右按鈕可連續移動',
      L.tip2: '使用硬降快速放置方塊',
      L.tip3: '使用暫存保留方塊稍後使用',
      L.tapToResume: '點擊繼續恢復遊戲',
      // Wallet Binding
      L.bindWallet: '綁定錢包',
      L.connectWallet: '連接錢包',
      L.unlockGlobalRank: '解鎖全球排名',
      L.bindDescription: '連接你的 Solana 錢包，解鎖全球排行榜和雲端同步功能。',
      L.benefitGlobalRanking: '全球排名',
      L.benefitCloudSync: '雲端分數同步',
      L.benefitAchievements: '成就系統',
      L.connectingWallet: '正在連接錢包...',
      L.binding: '正在綁定帳戶...',
      L.processing: '處理中...',
      L.openWalletApp: '請打開你的錢包應用確認連接',
      L.walletConnected: '錢包已連接',
      L.unbind: '解綁',
      L.unbindConfirm: '確定要解綁錢包嗎？你的雲端分數會保留，但需要重新綁定才能訪問。',
      L.cancel: '取消',
      // Sync Score
      L.syncScores: '同步分數',
      L.syncScoresDescription: '你有本地分數可以上傳到全球排行榜。選擇你想同步的分數。',
      L.selected: '已選擇',
      L.uploading: '上傳中...',
      L.upload: '上傳',
      L.uploadToGlobal: '上傳到全球榜',
      // Global Leaderboard
      L.localTab: '本地',
      L.globalTab: '全球',
      L.globalLocked: '連接錢包查看全球排名',
      L.bindNow: '立即綁定',
      L.willSyncToCloud: '將同步到全球排行榜',
      L.syncedToCloud: '已同步',
      L.submitting: '提交中...',
      // Wallet Picker
      L.selectWallet: '選擇錢包',
      L.selectWalletApp: '選擇錢包應用：',
      L.recommended: '推薦',
      L.bestMwaSupport: 'MWA 支援最佳',
      L.mwaSupported: '支援 MWA',
      L.deepLinkSupported: '支援深度連結',
      L.walletTip: '提示',
      L.walletTipContent: '如果自動打開了錯誤的錢包，請前往 設定 > 應用程式 > [錢包名稱] > 清除預設值，然後重試。',
      L.noWalletShowQr: '沒有錢包？顯示二維碼',
      L.downloadWallet: '下載錢包：',
      L.scanWithWallet: '使用錢包應用掃描',
      L.walletNotInstalled: '未安裝 {wallet}，請先從應用商店安裝。',
    },

    // Japanese
    AppLanguage.japanese: {
      L.gameTitle: 'サイバーブロック',
      L.startGame: 'ゲーム開始',
      L.settings: '設定',
      L.controls: '操作方法',
      L.leaderboard: 'ランキング',
      L.badges: 'バッジ',
      L.badgeUnlocked: '取得済み',
      L.badgeLocked: '未取得',
      L.tapToClose: 'タップで閉じる',
      L.errorConnectWalletFirst: '先にウォレットを接続してください',
      L.errorAuthFailed: '認証に失敗しました',
      L.errorLoadBadgesFailed: 'バッジの読み込みに失敗しました',
      L.exitConfirmTitle: 'ゲームを終了',
      L.exitConfirmMessage: '本当に終了しますか？',
      L.exitConfirmYes: '終了',
      L.exitConfirmNo: 'キャンセル',
      L.quit: '終了',
      L.paused: '一時停止',
      L.resume: '再開',
      L.restart: 'リスタート',
      L.mainMenu: 'メインメニュー',
      L.gameOver: 'ゲームオーバー',
      L.finalScore: '最終スコア',
      L.level: 'レベル',
      L.lines: 'ライン数',
      L.maxCombo: '最大コンボ',
      L.time: '時間',
      L.playAgain: 'もう一度',
      L.score: 'スコア',
      L.next: '次',
      L.hold: 'ホールド',
      L.combo: 'コンボ',
      L.settingsTitle: '設定',
      L.visual: 'ビジュアル',
      L.glowIntensity: 'グロー強度',
      L.glitchEffects: 'グリッチ効果',
      L.audio: 'オーディオ',
      L.soundEffects: '効果音',
      L.volume: '音量',
      L.music: '音楽',
      L.musicVolume: '音楽音量',
      L.hapticFeedback: '触覚フィードバック',
      L.language: '言語',
      L.languageSettings: '言語設定',
      L.controlsTitle: '操作方法',
      L.moveLeft: '左移動',
      L.moveRight: '右移動',
      L.softDrop: 'ソフトドロップ',
      L.hardDrop: 'ハードドロップ',
      L.rotateCW: '右回転',
      L.rotateCCW: '左回転',
      L.holdPiece: 'ホールド',
      L.pause: '一時停止',
      L.rank: '順位',
      L.playerName: 'プレイヤー',
      L.noRecords: '記録なし',
      L.playToRecord: 'ゲームをプレイして記録を作ろう！',
      L.newHighScore: 'ハイスコア更新',
      L.yourRank: 'あなたの順位：',
      L.enterName: '名前を入力',
      L.submit: '登録',
      L.skip: 'スキップ',
      L.touchControls: 'タッチ操作',
      L.tips: 'ヒント',
      L.tip1: '左/右ボタンを長押しで連続移動',
      L.tip2: 'ハードドロップで素早く配置',
      L.tip3: 'ホールドでピースを保持',
      L.tapToResume: '再開をタップして続ける',
      // Wallet Binding
      L.bindWallet: 'ウォレットを接続',
      L.connectWallet: 'ウォレットを接続',
      L.unlockGlobalRank: 'グローバルランクを解除',
      L.bindDescription: 'Solanaウォレットを接続して、グローバルランキングとクラウド同期機能を解除しましょう。',
      L.benefitGlobalRanking: 'グローバルランキング',
      L.benefitCloudSync: 'クラウドスコア同期',
      L.benefitAchievements: '実績',
      L.connectingWallet: 'ウォレットを接続中...',
      L.binding: 'アカウントを紐付け中...',
      L.processing: '処理中...',
      L.openWalletApp: 'ウォレットアプリを開いて接続を承認してください',
      L.walletConnected: 'ウォレット接続完了',
      L.unbind: '解除',
      L.unbindConfirm: 'ウォレットの紐付けを解除しますか？クラウドスコアは保持されますが、再度紐付けが必要になります。',
      L.cancel: 'キャンセル',
      // Sync Score
      L.syncScores: 'スコアを同期',
      L.syncScoresDescription: 'グローバルランキングにアップロードできるローカルスコアがあります。同期したいスコアを選択してください。',
      L.selected: '選択済み',
      L.uploading: 'アップロード中...',
      L.upload: 'アップロード',
      L.uploadToGlobal: 'グローバルにアップロード',
      // Global Leaderboard
      L.localTab: 'ローカル',
      L.globalTab: 'グローバル',
      L.globalLocked: 'ウォレットを接続してグローバルランキングを見る',
      L.bindNow: '今すぐ接続',
      L.willSyncToCloud: 'グローバルランキングに同期されます',
      L.syncedToCloud: '同期済み',
      L.submitting: '送信中...',
      // Wallet Picker
      L.selectWallet: 'ウォレットを選択',
      L.selectWalletApp: 'ウォレットアプリを選択：',
      L.recommended: 'おすすめ',
      L.bestMwaSupport: 'MWAサポート最良',
      L.mwaSupported: 'MWA対応',
      L.deepLinkSupported: 'ディープリンク対応',
      L.walletTip: 'ヒント',
      L.walletTipContent: '間違ったウォレットが自動的に開く場合は、設定 > アプリ > [ウォレット名] > デフォルトをクリアに移動して、もう一度お試しください。',
      L.noWalletShowQr: 'ウォレットがない？QRコードを表示',
      L.downloadWallet: 'ウォレットをダウンロード：',
      L.scanWithWallet: 'ウォレットアプリでスキャン',
      L.walletNotInstalled: '{wallet}がインストールされていません。アプリストアからインストールしてください。',
    },

    // Korean
    AppLanguage.korean: {
      L.gameTitle: '사이버 블록',
      L.startGame: '게임 시작',
      L.settings: '설정',
      L.controls: '조작법',
      L.leaderboard: '랭킹',
      L.badges: '배지',
      L.badgeUnlocked: '획득함',
      L.badgeLocked: '미획득',
      L.tapToClose: '아무 곳이나 탭하여 닫기',
      L.errorConnectWalletFirst: '먼저 지갑을 연결하세요',
      L.errorAuthFailed: '인증 실패',
      L.errorLoadBadgesFailed: '배지 로드 실패',
      L.quit: '종료',
      L.paused: '일시정지',
      L.resume: '계속',
      L.restart: '다시 시작',
      L.mainMenu: '메인 메뉴',
      L.gameOver: '게임 오버',
      L.finalScore: '최종 점수',
      L.level: '레벨',
      L.lines: '라인',
      L.maxCombo: '최대 콤보',
      L.time: '시간',
      L.playAgain: '다시 플레이',
      L.score: '점수',
      L.next: '다음',
      L.hold: '홀드',
      L.combo: '콤보',
      L.settingsTitle: '설정',
      L.visual: '비주얼',
      L.glowIntensity: '글로우 강도',
      L.glitchEffects: '글리치 효과',
      L.audio: '오디오',
      L.soundEffects: '효과음',
      L.volume: '볼륨',
      L.music: '음악',
      L.musicVolume: '음악 볼륨',
      L.hapticFeedback: '햅틱 피드백',
      L.language: '언어',
      L.languageSettings: '언어 설정',
      L.controlsTitle: '조작법',
      L.moveLeft: '왼쪽 이동',
      L.moveRight: '오른쪽 이동',
      L.softDrop: '소프트 드롭',
      L.hardDrop: '하드 드롭',
      L.rotateCW: '시계방향 회전',
      L.rotateCCW: '반시계방향 회전',
      L.holdPiece: '홀드',
      L.pause: '일시정지',
      L.rank: '순위',
      L.playerName: '플레이어',
      L.noRecords: '기록 없음',
      L.playToRecord: '게임을 플레이하여 기록을 세우세요!',
      L.newHighScore: '신기록',
      L.yourRank: '당신의 순위:',
      L.enterName: '이름 입력',
      L.submit: '등록',
      L.skip: '건너뛰기',
      L.touchControls: '터치 조작',
      L.tips: '팁',
      L.tip1: '왼쪽/오른쪽 버튼을 길게 눌러 연속 이동',
      L.tip2: '하드 드롭으로 빠르게 배치',
      L.tip3: '홀드로 블록을 나중에 사용',
      L.tapToResume: '계속을 눌러 재개',
      // Wallet Binding
      L.bindWallet: '지갑 연결',
      L.connectWallet: '지갑 연결',
      L.unlockGlobalRank: '글로벌 랭크 잠금 해제',
      L.bindDescription: 'Solana 지갑을 연결하여 글로벌 랭킹과 클라우드 동기화 기능을 잠금 해제하세요.',
      L.benefitGlobalRanking: '글로벌 랭킹',
      L.benefitCloudSync: '클라우드 점수 동기화',
      L.benefitAchievements: '업적',
      L.connectingWallet: '지갑 연결 중...',
      L.binding: '계정 연결 중...',
      L.processing: '처리 중...',
      L.openWalletApp: '지갑 앱을 열어 연결을 승인하세요',
      L.walletConnected: '지갑 연결됨',
      L.unbind: '연결 해제',
      L.unbindConfirm: '지갑 연결을 해제하시겠습니까? 클라우드 점수는 유지되지만 다시 연결해야 접근할 수 있습니다.',
      L.cancel: '취소',
      // Sync Score
      L.syncScores: '점수 동기화',
      L.syncScoresDescription: '글로벌 랭킹에 업로드할 수 있는 로컬 점수가 있습니다. 동기화할 점수를 선택하세요.',
      L.selected: '선택됨',
      L.uploading: '업로드 중...',
      L.upload: '업로드',
      L.uploadToGlobal: '글로벌에 업로드',
      // Global Leaderboard
      L.localTab: '로컬',
      L.globalTab: '글로벌',
      L.globalLocked: '지갑을 연결하여 글로벌 랭킹 보기',
      L.bindNow: '지금 연결',
      L.willSyncToCloud: '글로벌 랭킹에 동기화됩니다',
      L.syncedToCloud: '동기화됨',
      L.submitting: '제출 중...',
      // Wallet Picker
      L.selectWallet: '지갑 선택',
      L.selectWalletApp: '지갑 앱 선택:',
      L.recommended: '추천',
      L.bestMwaSupport: 'MWA 지원 최고',
      L.mwaSupported: 'MWA 지원',
      L.deepLinkSupported: '딥 링크 지원',
      L.walletTip: '팁',
      L.walletTipContent: '잘못된 지갑이 자동으로 열리면 설정 > 앱 > [지갑 이름] > 기본값 지우기로 이동한 후 다시 시도하세요.',
      L.noWalletShowQr: '지갑이 없으신가요? QR 코드 표시',
      L.downloadWallet: '지갑 다운로드:',
      L.scanWithWallet: '지갑 앱으로 스캔',
      L.walletNotInstalled: '{wallet}이(가) 설치되어 있지 않습니다. 앱 스토어에서 먼저 설치해 주세요.',
      // Exit Confirmation
      L.exitConfirmTitle: '게임 종료',
      L.exitConfirmMessage: '정말 종료하시겠습니까?',
      L.exitConfirmYes: '종료',
      L.exitConfirmNo: '취소',
    },

    // French
    AppLanguage.french: {
      L.gameTitle: 'CYBER BLOCKX',
      L.startGame: 'COMMENCER',
      L.settings: 'PARAMÈTRES',
      L.controls: 'CONTRÔLES',
      L.leaderboard: 'CLASSEMENT',
      L.badges: 'BADGES',
      L.badgeUnlocked: 'UNLOCKED',
      L.badgeLocked: 'LOCKED',
      L.tapToClose: 'Appuyez n\'importe où pour fermer',
      L.errorConnectWalletFirst: 'Veuillez d\'abord connecter votre portefeuille',
      L.errorAuthFailed: 'Échec de l\'authentification',
      L.errorLoadBadgesFailed: 'Échec du chargement des badges',
      L.quit: 'QUITTER',
      L.paused: 'PAUSE',
      L.resume: 'REPRENDRE',
      L.restart: 'RECOMMENCER',
      L.mainMenu: 'MENU PRINCIPAL',
      L.gameOver: 'FIN DE PARTIE',
      L.finalScore: 'Score Final',
      L.level: 'Niveau',
      L.lines: 'Lignes',
      L.maxCombo: 'Combo Max',
      L.time: 'Temps',
      L.playAgain: 'REJOUER',
      L.score: 'SCORE',
      L.next: 'SUIVANT',
      L.hold: 'RÉSERVE',
      L.combo: 'COMBO',
      L.settingsTitle: 'PARAMÈTRES',
      L.visual: 'VISUEL',
      L.glowIntensity: 'Intensité du halo',
      L.glitchEffects: 'Effets glitch',
      L.audio: 'AUDIO',
      L.soundEffects: 'Effets sonores',
      L.volume: 'Volume',
      L.music: 'Musique',
      L.musicVolume: 'Volume musique',
      L.hapticFeedback: 'Retour haptique',
      L.language: 'LANGUE',
      L.languageSettings: 'Langue',
      L.controlsTitle: 'CONTRÔLES',
      L.moveLeft: 'Gauche',
      L.moveRight: 'Droite',
      L.softDrop: 'Descente douce',
      L.hardDrop: 'Descente rapide',
      L.rotateCW: 'Rotation horaire',
      L.rotateCCW: 'Rotation anti-horaire',
      L.holdPiece: 'Réserve',
      L.pause: 'Pause',
      L.rank: 'Rang',
      L.playerName: 'Joueur',
      L.noRecords: 'Aucun record',
      L.playToRecord: 'Jouez pour établir un record!',
      L.newHighScore: 'NOUVEAU RECORD',
      L.yourRank: 'Votre rang:',
      L.enterName: 'ENTREZ VOTRE NOM',
      L.submit: 'VALIDER',
      L.skip: 'PASSER',
      L.touchControls: 'Contrôles tactiles',
      L.tips: 'Conseils',
      L.tip1: 'Maintenez les boutons gauche/droite pour un déplacement continu',
      L.tip2: 'Utilisez la descente rapide pour un placement rapide',
      L.tip3: 'Gardez une pièce en réserve pour plus tard',
      L.tapToResume: 'Appuyez sur REPRENDRE pour continuer',
      // Wallet Binding
      L.bindWallet: 'LIER PORTEFEUILLE',
      L.connectWallet: 'Connecter portefeuille',
      L.unlockGlobalRank: 'Débloquer le rang mondial',
      L.bindDescription: 'Connectez votre portefeuille Solana pour débloquer le classement mondial et la synchronisation cloud.',
      L.benefitGlobalRanking: 'Classement mondial',
      L.benefitCloudSync: 'Synchronisation cloud',
      L.benefitAchievements: 'Succès',
      L.connectingWallet: 'Connexion du portefeuille...',
      L.binding: 'Liaison du compte...',
      L.processing: 'Traitement...',
      L.openWalletApp: 'Ouvrez votre application de portefeuille pour approuver la connexion',
      L.walletConnected: 'Portefeuille connecté',
      L.unbind: 'Délier',
      L.unbindConfirm: 'Voulez-vous vraiment délier votre portefeuille? Vos scores cloud seront conservés mais vous devrez vous reconnecter pour y accéder.',
      L.cancel: 'Annuler',
      // Sync Score
      L.syncScores: 'Synchroniser scores',
      L.syncScoresDescription: 'Vous avez des scores locaux qui peuvent être téléchargés vers le classement mondial. Sélectionnez les scores à synchroniser.',
      L.selected: 'sélectionnés',
      L.uploading: 'Téléchargement...',
      L.upload: 'Télécharger',
      L.uploadToGlobal: 'Télécharger globalement',
      // Global Leaderboard
      L.localTab: 'LOCAL',
      L.globalTab: 'MONDIAL',
      L.globalLocked: 'Connectez votre portefeuille pour voir le classement mondial',
      L.bindNow: 'LIER MAINTENANT',
      L.willSyncToCloud: 'Sera synchronisé au classement mondial',
      L.syncedToCloud: 'Synchronisé',
      L.submitting: 'Envoi en cours...',
      // Wallet Picker
      L.selectWallet: 'Sélectionner portefeuille',
      L.selectWalletApp: 'Sélectionner portefeuille:',
      L.recommended: 'Recommandé',
      L.bestMwaSupport: 'Meilleur support MWA',
      L.mwaSupported: 'MWA supporté',
      L.deepLinkSupported: 'Deep link supporté',
      L.walletTip: 'Astuce',
      L.walletTipContent: 'Si le mauvais portefeuille s\'ouvre automatiquement, allez dans Paramètres > Applications > [Nom du portefeuille] > Effacer les valeurs par défaut, puis réessayez.',
      L.noWalletShowQr: 'Pas de portefeuille? Afficher QR',
      L.downloadWallet: 'Télécharger un portefeuille:',
      L.scanWithWallet: 'Scanner avec le portefeuille',
      L.walletNotInstalled: '{wallet} n\'est pas installé. Veuillez l\'installer depuis le store.',
      // Exit Confirmation
      L.exitConfirmTitle: 'Quitter le jeu',
      L.exitConfirmMessage: 'Voulez-vous vraiment quitter?',
      L.exitConfirmYes: 'QUITTER',
      L.exitConfirmNo: 'ANNULER',
    },

    // German
    AppLanguage.german: {
      L.gameTitle: 'CYBER BLOCKX',
      L.startGame: 'SPIEL STARTEN',
      L.settings: 'EINSTELLUNGEN',
      L.controls: 'STEUERUNG',
      L.leaderboard: 'RANGLISTE',
      L.badges: 'ABZEICHEN',
      L.badgeUnlocked: 'FREIGESCHALTET',
      L.badgeLocked: 'GESPERRT',
      L.tapToClose: 'Tippen Sie irgendwo, um zu schließen',
      L.errorConnectWalletFirst: 'Bitte verbinden Sie zuerst Ihre Wallet',
      L.errorAuthFailed: 'Authentifizierung fehlgeschlagen',
      L.errorLoadBadgesFailed: 'Fehler beim Laden der Abzeichen',
      L.quit: 'BEENDEN',
      L.paused: 'PAUSIERT',
      L.resume: 'FORTSETZEN',
      L.restart: 'NEUSTART',
      L.mainMenu: 'HAUPTMENÜ',
      L.gameOver: 'SPIEL VORBEI',
      L.finalScore: 'Endpunktzahl',
      L.level: 'Level',
      L.lines: 'Linien',
      L.maxCombo: 'Max Kombo',
      L.time: 'Zeit',
      L.playAgain: 'NOCHMAL',
      L.score: 'PUNKTE',
      L.next: 'NÄCHSTES',
      L.hold: 'HALTEN',
      L.combo: 'KOMBO',
      L.settingsTitle: 'EINSTELLUNGEN',
      L.visual: 'VISUELL',
      L.glowIntensity: 'Leuchtintensität',
      L.glitchEffects: 'Glitch-Effekte',
      L.audio: 'AUDIO',
      L.soundEffects: 'Soundeffekte',
      L.volume: 'Lautstärke',
      L.music: 'Musik',
      L.musicVolume: 'Musiklautstärke',
      L.hapticFeedback: 'Haptisches Feedback',
      L.language: 'SPRACHE',
      L.languageSettings: 'Sprache',
      L.controlsTitle: 'STEUERUNG',
      L.moveLeft: 'Links',
      L.moveRight: 'Rechts',
      L.softDrop: 'Sanftes Fallen',
      L.hardDrop: 'Schnelles Fallen',
      L.rotateCW: 'Im Uhrzeigersinn',
      L.rotateCCW: 'Gegen Uhrzeigersinn',
      L.holdPiece: 'Halten',
      L.pause: 'Pause',
      L.rank: 'Rang',
      L.playerName: 'Spieler',
      L.noRecords: 'Keine Rekorde',
      L.playToRecord: 'Spiele um einen Rekord aufzustellen!',
      L.newHighScore: 'NEUER HIGHSCORE',
      L.yourRank: 'Dein Rang:',
      L.enterName: 'NAME EINGEBEN',
      L.submit: 'BESTÄTIGEN',
      L.skip: 'ÜBERSPRINGEN',
      L.touchControls: 'Touch-Steuerung',
      L.tips: 'Tipps',
      L.tip1: 'Halten Sie die Links/Rechts-Tasten für kontinuierliche Bewegung',
      L.tip2: 'Nutzen Sie schnelles Fallen für schnelle Platzierung',
      L.tip3: 'Halten Sie ein Teil für später bereit',
      L.tapToResume: 'Drücken Sie FORTSETZEN um weiterzuspielen',
      // Wallet Binding
      L.bindWallet: 'WALLET VERBINDEN',
      L.connectWallet: 'Wallet verbinden',
      L.unlockGlobalRank: 'Globalen Rang freischalten',
      L.bindDescription: 'Verbinden Sie Ihr Solana-Wallet um die globale Rangliste und Cloud-Synchronisierung freizuschalten.',
      L.benefitGlobalRanking: 'Globale Rangliste',
      L.benefitCloudSync: 'Cloud-Punktestand',
      L.benefitAchievements: 'Erfolge',
      L.connectingWallet: 'Wallet wird verbunden...',
      L.binding: 'Konto wird verknüpft...',
      L.processing: 'Wird verarbeitet...',
      L.openWalletApp: 'Öffnen Sie Ihre Wallet-App um die Verbindung zu genehmigen',
      L.walletConnected: 'Wallet verbunden',
      L.unbind: 'Trennen',
      L.unbindConfirm: 'Möchten Sie die Wallet-Verbindung wirklich trennen? Ihre Cloud-Punkte bleiben erhalten, aber Sie müssen sich erneut verbinden um darauf zuzugreifen.',
      L.cancel: 'Abbrechen',
      // Sync Score
      L.syncScores: 'Punkte synchronisieren',
      L.syncScoresDescription: 'Sie haben lokale Punkte die zur globalen Rangliste hochgeladen werden können. Wählen Sie die Punkte zum Synchronisieren.',
      L.selected: 'ausgewählt',
      L.uploading: 'Hochladen...',
      L.upload: 'Hochladen',
      L.uploadToGlobal: 'Global hochladen',
      // Global Leaderboard
      L.localTab: 'LOKAL',
      L.globalTab: 'GLOBAL',
      L.globalLocked: 'Verbinden Sie Ihr Wallet um die globale Rangliste zu sehen',
      L.bindNow: 'JETZT VERBINDEN',
      L.willSyncToCloud: 'Wird mit globaler Rangliste synchronisiert',
      L.syncedToCloud: 'Synchronisiert',
      L.submitting: 'Wird gesendet...',
      // Wallet Picker
      L.selectWallet: 'Wallet wählen',
      L.selectWalletApp: 'Wallet-App wählen:',
      L.recommended: 'Empfohlen',
      L.bestMwaSupport: 'Beste MWA-Unterstützung',
      L.mwaSupported: 'MWA unterstützt',
      L.deepLinkSupported: 'Deep Link unterstützt',
      L.walletTip: 'Tipp',
      L.walletTipContent: 'Wenn automatisch das falsche Wallet geöffnet wird, gehen Sie zu Einstellungen > Apps > [Wallet-Name] > Standardeinstellungen löschen und versuchen Sie es erneut.',
      L.noWalletShowQr: 'Kein Wallet? QR-Code anzeigen',
      L.downloadWallet: 'Wallet herunterladen:',
      L.scanWithWallet: 'Mit Wallet-App scannen',
      L.walletNotInstalled: '{wallet} ist nicht installiert. Bitte installieren Sie es zuerst aus dem App Store.',
      // Exit Confirmation
      L.exitConfirmTitle: 'Spiel beenden',
      L.exitConfirmMessage: 'Möchten Sie wirklich beenden?',
      L.exitConfirmYes: 'BEENDEN',
      L.exitConfirmNo: 'ABBRECHEN',
    },
  };
}

// Convenience extension
extension LocalizationExtension on L {
  String get tr => LocalizationService.instance.tr(this);
}
